spring:
  application:
    name: sakila
  
  datasource:
    url: jdbc:postgresql://localhost:5432/pagila
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc: 
          time_zone: UTC
  
  graphql:
    graphiql:
      enabled: false  # Disable default GraphiQL
    path: /graphql
  
  mvc:
    static-path-pattern: /static/**
  
  thymeleaf:
    cache: false  # Disable cache for development
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  port: 9082

logging:
  level:
    com.sakila.analytics: DEBUG
    org.springframework.graphql: DEBUG
